title: Kai Barker
logo: /assets/img/headshot2.png
description: 
  I'm a data-driven problem solver with a passion for turning complex ideas into clean, impactful solutions—whether 
  that's through code, analytics, or creative collaboration. 
  Outside of tech, you'll find me on the court, climbing wall, or pickleball court. 
show_downloads: true
theme: jekyll-theme-minimal
